### ISSUE TITLE
Get Medical Help section Bugs

### ISSUE THREAD

**Issue by KenStarry** [podii-community/e-poultry#12]
### a) File Upload
Once a user clicks the prompt to pick images from the gallery, they are restricted to one image and the action cannot be undone.

#### Todo

- [ ] Allow user to pick multiple images from the gallery to comprehensively show the nature of the problem.
- [ ] Allow a user to delete picked images from the gallery (undo).

### b) Terms and conditions agreement error message

- [ ] When a user tries to click the request button before accepting the terms and conditions, it should display an error message to the user prompting them to accept the terms and conditions.

<img src="https://github.com/podii-community/e-poultry/assets/82617564/ff0057ad-dfda-40f7-99b9-ced07c1a05c9" width="35%"/>
